from nav_sim_modules import ENV_SIZE, RESOLUTION, MAP_OBS_VAL, MAP_PASS_VAL, MAP_UNK_VAL

MAP_SIZE = ENV_SIZE
MAP_RESOLUTION = RESOLUTION
FULL_RANGE = MAP_SIZE*MAP_RESOLUTION
HALF_RANGE = FULL_RANGE/2
MOVABLE_RANGE = HALF_RANGE/5